from dataclasses import dataclass
from typing import Optional, Union
from datetime import datetime
from enum import Enum

# GraphState never generates time.
# Execution timestamps are generated by the Runner.
# Domain-specific timestamps may be provided by Nodes.


class EventType(str, Enum):
    """Canonical event types emitted during execution."""
    NODE_STARTED = "node_started"
    NODE_COMPLETED = "node_completed"
    NODE_SKIPPED = "node_skipped"


@dataclass(frozen=True)
class Fact:
    key: str
    value: Union[str, int, float, bool]
    timestamp: datetime


@dataclass(frozen=True)
class Decision:
    description: str
    timestamp: datetime


@dataclass(frozen=True)
class Rejection:
    description: str
    reason: str
    timestamp: datetime


@dataclass(frozen=True)
class Event:
    type: EventType
    description: str
    timestamp: datetime


@dataclass(frozen=True)
class GraphState:
    trace_id: str
    intent: Optional[str]
    facts: tuple[Fact, ...]
    decisions: tuple[Decision, ...]
    rejections: tuple[Rejection, ...]
    events: tuple[Event, ...]

    def with_intent(self, intent: str) -> "GraphState":
        return GraphState(
            trace_id=self.trace_id,
            intent=intent,
            facts=self.facts,
            decisions=self.decisions,
            rejections=self.rejections,
            events=self.events,
        )

    def with_fact(self, fact: Fact) -> "GraphState":
        return GraphState(
            trace_id=self.trace_id,
            intent=self.intent,
            facts=self.facts + (fact,),
            decisions=self.decisions,
            rejections=self.rejections,
            events=self.events,
        )

    def with_decision(self, decision: Decision) -> "GraphState":
        return GraphState(
            trace_id=self.trace_id,
            intent=self.intent,
            facts=self.facts,
            decisions=self.decisions + (decision,),
            rejections=self.rejections,
            events=self.events,
        )

    def with_rejection(self, rejection: Rejection) -> "GraphState":
        return GraphState(
            trace_id=self.trace_id,
            intent=self.intent,
            facts=self.facts,
            decisions=self.decisions,
            rejections=self.rejections + (rejection,),
            events=self.events,
        )

    def with_event(self, event: Event) -> "GraphState":
        return GraphState(
            trace_id=self.trace_id,
            intent=self.intent,
            facts=self.facts,
            decisions=self.decisions,
            rejections=self.rejections,
            events=self.events + (event,),
        )

    @staticmethod
    def empty(trace_id: str) -> "GraphState":
        return GraphState(
            trace_id=trace_id,
            intent=None,
            facts=(),
            decisions=(),
            rejections=(),
            events=(),
        )
